### ISSUE TITLE
Finding Clone Detector

### ISSUE THREAD

**Issue by MatinMan** [MatinMan/JSClonesBugsAnalysis#1]
As a researcher I want to find tools for finding clones in JS in order to compare them 
Story Point: 3
Priority: 1
Very-risky
Estimation: 12 h

**Comment by monamvhd** [comment]
As a developer,, I want to fiind some tools for finding clones and compare them So I can find the best tool.

Task breakdown

 [] RawData: papers related to find clones (Development nature matters: An empirical study
of code clones in JavaScript applications & A Survey on Software Clone Detection Research)
 [] AttributesExtraction: 
 [] StoreLink: link the brief of he papers
 [] Model:
 [] Reporting: best tool for finding clones in JS

**Comment by monamvhd** [comment]
As I read the papers the best tool fo finding the clones in JS is JSCD

**Comment by ElnazTaqizadeh** [comment]
Here is summary of the paper that @monamvhd has mentioned above:

Most of code clones studies are limited to statically-typed languages such as Java, C, and C++. In addition, most previous studies did not consider different application domains such as standalone projects or web applications. 
In this paper, they attempt to work on these weaknesses and study JavaScript clones, for different application domains.
This paper provides us with a beneficial information like introducing a new clone detector that they developed for JavaScript and it’s publicly available (JSCD). Also they have considered standalone projects which are target applications for us.
