### ISSUE TITLE
Clones introduced by a dev

### ISSUE THREAD

**Issue by rigbypc** [MatinMan/JSClonesBugsAnalysis#10]
As a manager, I want to know which devs introduce the most clones, so I can understand who has expertise about which clones.

-[ ] Number of clones the developer introduced

clone <- files <- commit -> dev, bugs

Task breakdown
- [x] RawData: a simple JS project
[AngularJS]
(https://github.com/angular/angular.js.git)
- [x] AttributesExtraction: Clones from Story #5 and #6 
- [x] StoreLink: link the dev to the commit and to the file with clones 
- [x] Model: contribute this measure to the model Story #9 
- [x] Reporting: number of clones that a developer has introduced and their location (ie the file)

**Comment by ElnazTaqizadeh** [comment]
thanks @monamvhd but I've already extracted developer information that I need for this task and stored them in the developer table in database.

**Comment by monamvhd** [comment]
read this please #9

**Comment by ElnazTaqizadeh** [comment]
Data for modeling was not enough, so we've decided to repeat steps of this task on other projects in next iteration to get more reasonable result.
