### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by ElnazTaqizadeh** [MatinMan/JSClonesBugsAnalysis#15]
Please share your suggestion for data visualization tools here to decide which one is better for our project.

I checked [RAW](http://raw.densitydesign.org/).  It is open-source and doesn’t require any registration. 
I guess one of its advantage is that it doesn't require any coding. You just copy & paste result tables and customize their chart based on your purpose.There is a short video on their website that you can learn from.
Here I've attached an example, but I think it's better to try it with results from bugs-clone.
In this model we have information about developers, their experience (color) and number of their clones (Size)
![ss](https://cloud.githubusercontent.com/assets/10716012/14152026/f05f8b4a-f67e-11e5-8c07-eedfe8b39061.png)

**Comment by MatinMan** [comment]
http://www.tableau.com/ <http://www.tableau.com/>

https://plot.ly/ <https://plot.ly/>

manam ina ro peida kardam mikhai y niga bndda to ham age dus dari moghayese kon :)

**Comment by ElnazTaqizadeh** [comment]
@MatinMan did you compare tableau and plot together?which one do you prefer?
I think we can omit RAW, because plot has more charts and options. we can upload our CVS data and work on that.
Even it's free plan would be ok for us :)
