### ISSUE TITLE
Number of bug

### ISSUE THREAD

**Issue by MatinMan** [MatinMan/JSClonesBugsAnalysis#6]
As a manager, I want to know the number of bugs per file so the bug density for the system

Story points:5
Priorit: high
risk: medium

Task breakdown
- [x] RawData: a simple JS project (same as in story #5 and 
[Uploading logs.txt…]()
)
- [x] AttributesExtraction: extract the bug numbers from the commits 
- [x] StoreLink: link the bugs to the files and count the number of bugs per file
- [ ] Model: 
- [ ] Reporting: the number of bugs per file

**Comment by MatinMan** [comment]
the tool was so tricky it took lots of time to run it properly.
there are different property for tool's configuration right now i am using: similarly= 0.9, STRIDE='0', MIN_TOKENS='50 100'

**Comment by monamvhd** [comment]
For finding bus in [https://github.com/MatinMan/JSClonesBugsAnalysis/blob/master/RawData/logs.txt](url) , [https://github.com/MatinMan/JSClonesBugsAnalysis/blob/master/AttributeExtraction/bugInFile.pl](url) should be run

**Comment by monamvhd** [comment]
- [ ] inserting log file info into database:

( create 3 table files,bug_files,bugs - insert into them)

estimate : 2 days
risk : low
priority: 1

**Comment by monamvhd** [comment]
the backup of database containing log info data 

[https://github.com/MatinMan/JSClonesBugsAnalysis/tree/master/StoreLink](url)

**Comment by ElnazTaqizadeh** [comment]
@monamvhd I restore my "clones" database with the backup file you've committed. To make sure everything is the same, you have 4 tables:

1. bugs(commit, bug)
2. bugsPerFile(fileNeme, bugNo)
3. clonesPerFile(fileName, clonesNo)
4. files(commit, path, add, remove)

right?
and I can count number of bugs per file from which table?!from the above list it seems I should work on bugsPerFile but in your database, you didn't relate bugs and files (which bug related to which file)

**Comment by monamvhd** [comment]
@ElnazTaqizadeh 
bugsPerFile, is the table that you created before. 
you need join bugs and files table and group  them by commit. and count bugs  and insert this value in bugsPerFile

**Comment by ElnazTaqizadeh** [comment]
@monamvhd yeah I know, I wanted to make sure whether you insert data on them or I should do.
I'm working on that ;)

**Comment by ElnazTaqizadeh** [comment]
- [x]  counting number of bugs for each file

estimate : 1 day
risk : low
priority: 2

1, I've joined data from tables: files and bugs. find out each bug related to which files, and stored them in "bugPerFile" table.
2, Through a SQL query I've have returned number of bugs related to each files and printed them in a tabular format.
