### ISSUE TITLE
Do bugs correlate with Clones

### ISSUE THREAD

**Issue by MatinMan** [MatinMan/JSClonesBugsAnalysis#7]
As a dev, I want to know if there is a relationship between the number of bugs in a file and the number of clones, so that I can decide if it is worthwhile to get rid of clones

Do a correlation between the output of Story #5 and Story #6

**Comment by rigbypc** [comment]
Number of bugs linked with number of clones at the file level

**Comment by rigbypc** [comment]
correlation at .45, link to data
