### ISSUE TITLE
Basic Confounds

### ISSUE THREAD

**Issue by rigbypc** [MatinMan/JSClonesBugsAnalysis#9]
As a manager, I want to understand which traditional factors affect the number of bugs, so that I can control for these when determine how many bugs occur with clones

-[x] Churn, changes to file
-[x] Developer experience
-[] Add two more

- [x] RawData: a simple JS project
[AngularJS]
(https://github.com/angular/angular.js.git)
- [x] AttributesExtraction: Add to parser that was developed in Story #6  -> [dev tables](https://github.com/MatinMan/JSClonesBugsAnalysis/blob/master/AttributeExtraction/devTables.sql) , [bugInFile.pl](https://github.com/MatinMan/JSClonesBugsAnalysis/blob/master/AttributeExtraction/bugInFile.pl)
- [x] StoreLink: link each attribute to the file (primary and indexes) [developerExp.sql](https://github.com/MatinMan/JSClonesBugsAnalysis/blob/master/StoreLink/DeveloperExprience.sql)  , [File_Churn.sql](https://github.com/MatinMan/JSClonesBugsAnalysis/blob/master/StoreLink/Files_Churn.sql)
- [x] Model: bugs ~ churn + dev_exp + dev_clones + num_clones (unit = file) 
[CreateDataset.sql](https://github.com/MatinMan/JSClonesBugsAnalysis/blob/master/Model/CreateDataset.sql),
[bugclonemodel.R](https://github.com/MatinMan/JSClonesBugsAnalysis/blob/master/Model/bugclonemodel.R),
[dataset](https://github.com/MatinMan/JSClonesBugsAnalysis/blob/master/Model/clonesAtts.csv)
- [x] Reporting: [readme.md] (https://github.com/MatinMan/JSClonesBugsAnalysis/blob/master/Model/README.md)

**Comment by monamvhd** [comment]
For finding the Churn we need number of lines added to the file and number of files remove from the file so I modified [bugInFile.pl](https://github.com/MatinMan/JSClonesBugsAnalysis/blob/master/AttributeExtraction/bugInFile.pl)

**Comment by monamvhd** [comment]
For developer experience we need author information and date of each commit 
I modified [bugInFile.pl](https://github.com/MatinMan/JSClonesBugsAnalysis/blob/master/AttributeExtraction/bugInFile.pl)
To also get developer information and insert them in [dev tables](https://github.com/MatinMan/JSClonesBugsAnalysis/blob/master/AttributeExtraction/devTables.sql)

**Comment by monamvhd** [comment]
retrive developer expirience with [deleoperExp.sql](https://github.com/MatinMan/JSClonesBugsAnalysis/blob/master/StoreLink/DeveloperExprience.sql)

**Comment by monamvhd** [comment]
add relation -store link developer experience to the file  with [deleoperExp.sql](https://github.com/MatinMan/JSClonesBugsAnalysis/blob/master/StoreLink/DeveloperExprience.sql)

**Comment by monamvhd** [comment]
store link File_Churn [File_Churn.sql](https://github.com/MatinMan/JSClonesBugsAnalysis/blob/master/StoreLink/Files_Churn.sql)

**Comment by monamvhd** [comment]
I did the Attribute extaction and store link in milestone 2 and modeling and reporting in milestone 3
